# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2e4c65c4-6d57-42cd-92e6-9ece8fd70032";
      fsType = "btrfs";
      options = [ "subvol=@" "rw" "noatime" "discard=async" "compress-force=zstd" "space_cache=v2" "commit=120" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/2e4c65c4-6d57-42cd-92e6-9ece8fd70032";
      fsType = "btrfs";
      options = [ "subvol=@home" "rw" "noatime" "discard=async" "compress-force=zstd" "space_cache=v2" "commit=120" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/2e4c65c4-6d57-42cd-92e6-9ece8fd70032";
      fsType = "btrfs";
      options = [ "subvol=@nix" "rw" "noatime" "discard=async" "compress-force=zstd" "space_cache=v2" "commit=120" ];
    };

  fileSystems."/etc/nixos" =
    { device = "/dev/disk/by-uuid/2e4c65c4-6d57-42cd-92e6-9ece8fd70032";
      fsType = "btrfs";
      options = [ "subvol=@nixos-config" "rw" "noatime" "discard=async" "compress-force=zstd" "space_cache=v2" "commit=120" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/2e4c65c4-6d57-42cd-92e6-9ece8fd70032";
      fsType = "btrfs";
      options = [ "subvol=@log" "rw" "noatime" "discard=async" "compress-force=zstd" "space_cache=v2" "commit=120" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/58D6-8CFC";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/2681194f-6e6e-4b15-9817-fecfa7a107a4"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}